# -*- coding: utf-8 -*-
"""magic.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FspGjTx6NHnB1irvbY6oafgDMJW3gBZf
"""

pip install tableone

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from collections import Counter
from tableone import TableOne

# %matplotlib inline

#load dataset drug
df19 = pd.read_csv('/content/NSDUH_2019_Tab.csv',sep = '	'  )
df19.info()

#df19.to_csv('data2019.csv')

#df19.to_csv('NSDUH2019.csv')

#load dataset drug
df20 = pd.read_csv('/content/NSDUH_2020_Tab.csv',sep = '	'  )
df20.info()

#df20 =df20[['CIGEVER','CIGTRY','CIGAGE','ALCEVER','PSILCY']]
#CIGEVER-cat,CIGTRY-num,,CIGAGE - num'
#df20.info()

df20.head()

df20.PSILCY.unique()

#df20_1['CIGWILYR'] = df20_1['CIGWILYR'].astype('category')
#df20_1['CIGOFRSM'] = df20_1['CIGOFRSM'].astype('category')

#mytable = TableOne(df20, columns=columns ,nonnormal= nonnormal , groupby=groupby, pval=True)

#Len : 2 EVER USED PSILOCYBIN (MUSHROOMS) 
#1 = Yes
#2 = no
#3 = Yes LOGICALLY ASSIGNED
drug20= df20[(df20['PSILCY']== 1) | (df20['PSILCY'] == 3) | (df20['PSILCY'] == 2) |(df20['PSILCY'] == 91)]
drug20.nunique

drug19= df19[(df19['PSILCY']== 1) | (df19['PSILCY'] == 3) | (df19['PSILCY'] == 2) |(df19['PSILCY'] == 91)]
drug19.nunique

drug20['PSILCY'] = drug20['PSILCY'].apply(lambda x:1 if(x == 1  or x == 3) else 0)
drug19['PSILCY'] = drug19['PSILCY'].apply(lambda x:1 if(x == 1  or x == 3) else 0)

drug20.loc[drug20['ALCYRTOT'] > 900, 'ALCYRTOT'] = np.nan
drug20.loc[drug20['MJAGE']> 980,'MJAGE'] = np.nan
drug20.loc[drug20['ALDAYPMO'] > 50, 'ALDAYPMO'] = np.nan
drug20.loc[drug20['ALCUS30D'] > 86, 'ALCUS30D'] = np.nan
drug20.loc[drug20['BMI2'] > 70, 'BMI2'] = np.nan
drug20.loc[drug20['WRKDHRSWK2'] > 62, 'WRKDHRSWK2'] = np.nan
drug20.loc[drug20['CIGAGE'] > 900, 'CIGAGE'] = np.nan
drug20.loc[drug20['NOMARR2'] > 80, 'NOMARR2'] = np.nan
drug20.loc[drug20['MJEVER'] > 80, 'MJEVER'] = np.nan
drug20.loc[drug20['ALCEVER'] > 80, 'ALCEVER'] = np.nan
drug20.loc[drug20['SMKLSSEVR'] > 90, 'SMKLSSEVR'] = np.nan
drug20.loc[drug20['CIGTRY'] > 900, 'CIGTRY'] = np.nan
drug20.loc[drug20['CADRKDRUG'] > 80, 'CADRKDRUG'] = np.nan
drug20.loc[drug20['HEREVER'] >= 90, 'HEREVER'] = np.nan
drug20.loc[drug20['CRKEVER'] >= 90, 'CRKEVER'] = np.nan
drug20.loc[drug20['COCEVER'] >= 90, 'COCEVER'] = np.nan
drug20.loc[drug20['HLTINMNT'] >= 90, 'HLTINMNT'] = np.nan
drug20.loc[drug20['HLTINDRG'] >= 90, 'HLTINDRG'] = np.nan
drug20.loc[drug20['HLTINALC'] >= 90, 'HLTINALC'] = np.nan
drug20.loc[drug20['WRKSTATWK2'] >= 9, 'WRKSTATWK2'] = np.nan
drug20.loc[drug20['DIFFERAND'] >= 80, 'DIFFERAND'] = np.nan
drug20.loc[drug20['DIFFTHINK'] >= 80, 'DIFFTHINK'] = np.nan
drug20.loc[drug20['SEXIDENT'] >= 80, 'SEXIDENT'] = np.nan

drug20.loc[drug20['HEALTH'] >= 90, 'HEALTH'] = np.nan
drug20.loc[drug20['SEXAGE'] >= 5, 'SEXAGE'] = np.nan

drug20['EDUSCHLGO'] = drug20['EDUSCHLGO'].apply(lambda x : 1 if x == 1  or x == 11 else ( 2 if x == 2 else np.nan))
drug19['EDUSCHLGO'] = drug20['EDUSCHLGO'].apply(lambda x : 1 if x == 1  or x == 11 else ( 2 if x == 2 else np.nan))
#lambda x : x*2 if x < 10 else (x*3 if x < 20 else x)

drug19.loc[drug19['ALCYRTOT'] > 900, 'ALCYRTOT'] = np.nan
drug19.loc[drug19['MJAGE']> 980,'MJAGE'] = np.nan
drug19.loc[drug19['ALDAYPMO'] > 50, 'ALDAYPMO'] = np.nan
drug19.loc[drug19['ALCUS30D'] > 86, 'ALCUS30D'] = np.nan
drug19.loc[drug19['BMI2'] > 70, 'BMI2'] = np.nan
drug19.loc[drug19['WRKDHRSWK2'] > 62, 'WRKDHRSWK2'] = np.nan
drug19.loc[drug19['CIGAGE'] > 900, 'CIGAGE'] = np.nan
drug19.loc[drug19['NOMARR2'] > 80, 'NOMARR2'] = np.nan
drug19.loc[drug19['MJEVER'] > 80, 'MJEVER'] = np.nan
drug19.loc[drug19['ALCEVER'] > 80, 'ALCEVER'] = np.nan
drug19.loc[drug19['SMKLSSEVR'] > 90, 'SMKLSSEVR'] = np.nan
drug19.loc[drug19['CIGTRY'] > 900, 'CIGTRY'] = np.nan
drug19.loc[drug19['CADRKDRUG'] > 80, 'CADRKDRUG'] = np.nan
drug19.loc[drug19['HEREVER'] >= 90, 'HEREVER'] = np.nan
drug19.loc[drug19['CRKEVER'] >= 90, 'CRKEVER'] = np.nan
drug19.loc[drug19['COCEVER'] >= 90, 'COCEVER'] = np.nan
drug19.loc[drug19['HLTINMNT'] >= 90, 'HLTINMNT'] = np.nan
drug19.loc[drug19['HLTINDRG'] >= 90, 'HLTINDRG'] = np.nan
drug19.loc[drug19['HLTINALC'] >= 90, 'HLTINALC'] = np.nan
drug19.loc[drug19['WRKSTATWK2'] >= 9, 'WRKSTATWK2'] = np.nan
drug19.loc[drug19['DIFFERAND'] >= 80, 'DIFFERAND'] = np.nan
drug19.loc[drug19['DIFFTHINK'] >= 80, 'DIFFTHINK'] = np.nan
drug19.loc[drug19['SEXIDENT'] >= 80, 'SEXIDENT'] = np.nan
drug19.loc[drug19['HEALTH'] >= 90, 'HEALTH'] = np.nan
drug19.loc[drug19['SEXAGE'] >= 5, 'SEXAGE'] = np.nan



columns = ['PSILCY','CIGTRY','CIGAGE','SMKLSSEVR','ALCEVER','ALCYRTOT','ALCUS30D','MJEVER','MJAGE','BMI2','NOMARR2','CADRKDRUG','SEXAGE','NEWRACE2',
           'SEXRACE','HEALTH','EDUSCHLGO','SEXIDENT','DIFFTHINK','DIFFERAND','IREDUHIGHST2','WRKSTATWK2','WRKDHRSWK2','HLTINALC','HLTINDRG','HLTINMNT'
           ,'COCEVER','CRKEVER','HEREVER']
categorical = ['SMKLSSEVR','ALCEVER','MJEVER','NOMARR2','CADRKDRUG','SEXAGE','NEWRACE2','SEXRACE','HEALTH','EDUSCHLGO','SEXIDENT','DIFFTHINK'
            ,'DIFFERAND','IREDUHIGHST2','WRKSTATWK2','HLTINALC','HLTINDRG','HLTINMNT','COCEVER','CRKEVER','HEREVER']
groupby = 'PSILCY'
nonnormal = []
labels={'CIGTRY': 'FIRST_SMOKED','CIGAGE':'STARTSMOKEE','SMKLSSEVR':'SMOKELESS_TOBACCO','ALCEVER':'Ever_Alcohol','ALCYRTOT':'Total_Drinkday',
        'MJEVER':'MariJuana_ever','MJAGE':'first_Marijuana','BMI2':'BMI','NOMARR2':'Number_Marry_Times','CADRKDRUG':'Drug_When_Drink','SEXAGE':'Sex&Age'
        ,'NEWRACE2':'Race','SEXRACE':'Sex&Race','HEALTH':'Health_Condition','EDUSCHLGO':'Currently_School','SEXIDENT':'SEXUAL IDENTITY','DIFFTHINK':'Difficult_Thinking',
        'DIFFERAND':'Difficult_Doing_Errand','IREDUHIGHST2':'EDUCATION-RECODED_IMPUTATION_REVISED','WRKSTATWK2':'WORK_SITUATION_PastWeek',
        'WRKDHRSWK2':'Work_Hours_lastweek','HLTINALC':'ALCOHOL ABUSE OR ALCOHOLISM','HLTINDRG':'HLTINDRG','HLTINMNT':'MENTAL OR EMOTIONAL DIFFICULTIES'
        ,'COCEVER':'Everuse_Cocain','CRKEVER':'EverUseCrack','HEREVER':'EverUseHeroin'}

mytable19 = TableOne(drug19, columns=columns ,categorical = categorical,missing= True,rename= labels, nonnormal= nonnormal ,pval=True, groupby=groupby,htest_name=True,row_percent= True,tukey_test = True,dip_test= True,normal_test= True)

print(mytable19.tabulate(tablefmt="fancy_grid"))

mytable19.to_csv('mytable2019.csv')

mytable20 = TableOne(drug20, columns=columns ,categorical = categorical,missing= True,rename= labels, nonnormal= nonnormal ,pval=True, groupby=groupby,htest_name=True,row_percent= True,tukey_test = True,dip_test= True,normal_test= True)

print(mytable20.tabulate(tablefmt="fancy_grid"))

mytable20.to_csv('mytable2020.csv')

mytable = TableOne(df20, columns=columns ,nonnormal= nonnormal , groupby=groupby, pval=True)